import os
import subprocess

# Задаем переменные окружения
os.environ["AMOCRM_CLIENT_ID"] = "c01ffeea-9bbd-4efe-83fd-ae25ae3335c9"
os.environ["AMOCRM_SECRET"] = "U1ROdUISrn1zxva95gZNHVFTqyvo9AB4PqsbMqQAsaTb6QvvHBjFNvtGLI5Zwh9T"
os.environ["AMOCRM_SUBDOMAIN"] = "vbr07"
os.environ["AMOCRM_REDIRECT_URL"] = "https://dompluse.com/"
os.environ["AMOCRM_CODE"] = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImRjNWUxMzMyNTc1MmVlMDdhMGI3NDkzOTdkODVkN2RiNzI4Y2IzNzI2OThkODgxMGJjNjU5YWQzNzNiMDE0ZjMwOTZlMDA2M2Y0MTA5NWNmIn0.eyJhdWQiOiJjMDFmZmVlYS05YmJkLTRlZmUtODNmZC1hZTI1YWUzMzM1YzkiLCJqdGkiOiJkYzVlMTMzMjU3NTJlZTA3YTBiNzQ5Mzk3ZDg1ZDdkYjcyOGNiMzcyNjk4ZDg4MTBiYzY1OWFkMzczYjAxNGYzMDk2ZTAwNjNmNDEwOTVjZiIsImlhdCI6MTc1MTY2NDIyMSwibmJmIjoxNzUxNjY0MjIxLCJleHAiOjE3NTE3NTA2MjEsInN1YiI6IjExMDAwMjk4IiwiZ3JhbnRfdHlwZSI6IiIsImFjY291bnRfaWQiOjMxNzI4NTE4LCJiYXNlX2RvbWFpbiI6ImFtb2NybS5ydSIsInZlcnNpb24iOjIsInNjb3BlcyI6WyJwdXNoX25vdGlmaWNhdGlvbnMiLCJmaWxlcyIsImNybSIsImZpbGVzX2RlbGV0ZSIsIm5vdGlmaWNhdGlvbnMiXSwiaGFzaF91dWlkIjoiYjYxNDgzZDEtYmNmYy00MzRkLWExYjItNjQwNWYzZThlZjgwIiwiYXBpX2RvbWFpbiI6ImFwaS1iLmFtb2NybS5ydSJ9.TuZzwZ2gzYhl3Eo-QM-edtlxc52plK2RXOqWKRRDARMy8zhBsnC1mMf733mLV_Z2WQrEPtALFVMobpzQY3i3VKNEm5YFopIiBnlFWEL_EeTSqnTEXVkX3l_xfXu87_9-p0E-BLp5Wit5ayGps2K33LOVcmyzFYYu2GOtmUAnQrXOS8QDKhAiWyisv93kdc4Ngp8N3VLe2_PE-Gr9y8gFm5oNCEhdyNI5sQGTwlCP1qk9zx95HUUakcOU8xzDltcLWrlqoA4kOMuYKLjztwBNi0P32Opa9pyDQliYN0_dRPRY4VqtSr2HfjDexzyQvBi21bopX1GmtsAnqgiSllHnoA"

# Выполнение команды pyamogen
subprocess.run(["pyamogen", ">", "models.py"], shell=True)
